cache: 
  enable: true

scheme: Pisces

favicon:
small: /images/favicon-16x16-next.png
medium: /images/favicon-32x32-next.png
apple_touch_icon: /images/apple-touch-icon-next.png
safari_pinned_tab: /images/logo.svg
android_manifest: /images/manifest.json

menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive
  Docs:
    default: /docs/ || fa fa-book
  Getting Started:
    default: /getting-started/ || fa fa-flag
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags

menu_settings:
  icons: true
  badges: true

open_gragh:
  enable: true
  options:
    type: blog

# Local search
# Dependencies: https://github.com/next-theme/hexo-generator-searchdb
local_search:
  enable: true
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false

# Gitalk
# For more information: https://gitalk.github.io
gitalk:
  enable: true
  github_id: NewerLsg # GitHub repo owner
  repo: blog_comments # Repository name to store issues
  client_id: 368295582269d448f3ca  # GitHub Application Client ID
  client_secret: 04979a7fc51349a092ebba89aa6242417e0324d7 # GitHub Application Client Secret
  admin_user: NewerLsg # GitHub repo owner and collaborators, only these guys can initialize gitHub issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  #proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy address
  proxy: https://vercel.prohibitorum.top/github_access_token
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

